version: '3.8'

services:
  db:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: datathon_user
      POSTGRES_PASSWORD: datathon_password
      POSTGRES_DB: datathon_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5555:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  pgdata:
