"use client";
import React from "react";
import NetworkGraph from "./NetworkGraph";

interface PrintableReportProps {
  queryData: any;
  role: string;
}

export const PrintableReport = React.forwardRef<HTMLDivElement, PrintableReportProps>(
  ({ queryData, role }, ref) => {
    if (!queryData) return <div ref={ref}></div>;

    const date = new Date().toLocaleString();

    return (
      <div ref={ref} className="p-10 bg-white text-black font-sans min-h-screen">
        {/* Official Header */}
        <div className="border-b-2 border-slate-800 pb-4 mb-6">
          <div className="flex justify-between items-end">
            <div>
              <h1 className="text-3xl font-bold uppercase tracking-widest text-slate-900">Official Investigation Report</h1>
              <p className="text-sm font-medium text-slate-500 mt-1">Karnataka Police Data Analysis System</p>
            </div>
            <div className="text-right text-sm text-slate-600">
              <p><strong>Generated By Role:</strong> {role}</p>
              <p><strong>Date:</strong> {date}</p>
              <p><strong>Report ID:</strong> {Math.random().toString(36).substr(2, 9).toUpperCase()}</p>
            </div>
          </div>
        </div>

        {/* AI Synthesis Summary */}
        <div className="mb-8">
          <h2 className="text-xl font-semibold mb-3 border-b border-slate-300 pb-2">1. Executive Summary</h2>
          <div className="bg-slate-50 p-4 rounded border border-slate-200">
            <p className="text-slate-800 leading-relaxed mb-4">{queryData.answer_english}</p>
            {queryData.answer_kannada && (
              <div className="border-t border-slate-200 pt-3">
                <p className="text-xs text-slate-500 uppercase tracking-wider mb-1">Kannada Translation</p>
                <p className="text-slate-700">{queryData.answer_kannada}</p>
              </div>
            )}
          </div>
        </div>

        {/* AI Audit Trail */}
        <div className="mb-8">
          <h2 className="text-xl font-semibold mb-3 border-b border-slate-300 pb-2">2. AI Verification Trail</h2>
          <ul className="list-disc pl-5 space-y-1 text-sm text-slate-700">
            {queryData.audit_trail?.map((step: string, idx: number) => (
              <li key={idx}>{step}</li>
            ))}
          </ul>
        </div>

        {/* Network Graph Visual (if applicable) */}
        {queryData.intent === "network" && queryData.raw_data && (
          <div>
            <h2 className="text-xl font-semibold mb-3 border-b border-slate-300 pb-2">3. Network Topology</h2>
            {/* We render a static-looking version of the graph for print. Cytoscape can sometimes be tricky to print, but giving it a fixed height helps. */}
            <div className="h-[500px] border border-slate-300 bg-slate-50 rounded">
              <NetworkGraph data={queryData.raw_data} />
            </div>
          </div>
        )}

        {/* Footer */}
        <div className="mt-12 pt-4 border-t border-slate-300 text-center text-xs text-slate-500">
          CONFIDENTIAL - FOR INTERNAL POLICE USE ONLY
        </div>
      </div>
    );
  }
);

PrintableReport.displayName = "PrintableReport";
